[phases.setup]
nixPkgs = [
  "python311Full",
  "python311Packages.pip",
  "python311Packages.setuptools",
  "python311Packages.wheel",
  "gcc"
]

[phases.install]
cmds = ["python -m pip install -r requirements.txt"]

[start]
cmd = "python -m gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
