# Generated by Django 5.2.4 on 2025-08-12 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('photo', models.ImageField(blank=True, upload_to='blogs_image/', verbose_name='Фотка')),
                ('main_text', models.TextField(blank=True, verbose_name='Главный текст')),
                ('file', models.FileField(blank=True, upload_to='blogs_file/', verbose_name='Файл(необязательно)')),
            ],
            options={
                'verbose_name_plural': 'Блоги',
            },
        ),
        migrations.CreateModel(
            name='AboutCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.subject', verbose_name='Курс')),
            ],
            options={
                'verbose_name_plural': 'Описание курсов',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.subject', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('file', models.FileField(default='default.pdf', upload_to='homework/', verbose_name='Файл')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий учителя')),
                ('checked', models.BooleanField(default=False, verbose_name='Проверен: да/нет')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_homeworks', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name_plural': 'Домашние работы',
            },
        ),
        migrations.CreateModel(
            name='LessonTaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lesson_tasks/', verbose_name='Прикрепите файлы домашней работы')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_files', to='main.lesson')),
            ],
            options={
                'verbose_name': 'Файл домашней работы',
                'verbose_name_plural': 'Файлы домашней работы',
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_url', models.URLField(verbose_name='Ссылка на библиотеку')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.subject', verbose_name='Курс')),
            ],
            options={
                'verbose_name_plural': 'Библиотека',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.subject', verbose_name='Курс')),
            ],
            options={
                'verbose_name_plural': 'Модули',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.module', verbose_name='Модуль'),
        ),
    ]
