# Generated by Django 5.2.4 on 2025-08-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_lessontaskfile_task_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessontaskfile',
            name='task_url',
        ),
        migrations.AddField(
            model_name='lesson',
            name='task_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на практические задания'),
        ),
    ]
