# Generated by Django 5.2.4 on 2025-08-13 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_lessontaskfile_task_url_lesson_task_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='library_url',
        ),
        migrations.AddField(
            model_name='library',
            name='author',
            field=models.CharField(blank=True, max_length=255, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='library',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='LibraryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='library_files/', verbose_name='Прикрепите файлы книг')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='main.library', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Файл книги',
                'verbose_name_plural': 'Файлы книг',
            },
        ),
    ]
